### ISSUE TITLE
Connection diagram

### ISSUE THREAD

**Issue by migabc** [romor/blind-control#1]
> The Somfy Telis 5 RTS provides the interface to the radio signal. I use this unit as it is and just solder wires to the button lines to control them automatically. The buttons seem to be connected to pull up resistors and close contact to ground if pressed. Therefore, I soldered wires to each button and the GND connection. Notice that the Somfy Telis remote is powered by the Raspberry Pi. Its battery is removed and the contacts are connected to the 3.3 V supply of the RPi. There are 2 good places to put the supply wires on, with holes where they can easily be soldered.

Can you please provide the connection diagram on the Somfy remote - which terminals on the Somfy remote did you solder? (the picture you provided is difficult to see)

> These wires are connected to the GPIO interface of a Raspberry Pi. To simulate a button press, the GPIO pin of the RPi is set to zero, to release the button again the GPIO pin is set to high impedance state (thus reconfigured as input).

Are you using limiting resistors or just connecting directly to the GPIOs?

**Comment by romor** [comment]
Ad soldering at the Somfy remote:
I put one wire to each of the 4 buttons (up, down, my, channel). In addition, I soldered 2 wires for the power connection (GND, 3.3 V). So, 6 wires, nothing more. Just let me know if it is still difficult for you to identify the wires on the picture.
Supplying the remote control by the RPi is optional. You could also keep the battery of the remote control and just connect the GND line (but I do not see an advantage and reason to do so).

> Are you using limiting resistors or just connecting directly to the GPIOs?

No, I do not use resistors or other components. The wires go directly from the buttons to the GPIO pins and the supply pins are also directly attached.

My system is in operation now for more than 3 years. No problems so far, it works well.

**Comment by migabc** [comment]
Thanks a lot for your feedback.
I'm currently performing something similar but with a normal single channel Velux remote.
I'm going to need to control 2 additional binds (3 in total) and instead of buying 2 more remotes, I was thinking of using a Somfy 5 channel remote (like in your project). But I then saw that the Somfy Telis 5 RTS is actually more expensive than the 3 normal single channel remotes, so I think I'll just replicate the GPIOs on the RPI. 

Advantage: No need to worry about changing the RF channel nor worry about the channel switching delays.
Disadvantage: End up using more GPIO pins on the RPI (open, close, stop) x 3
