### ISSUE TITLE
what am I doing wrong? :sweat_smile:

### ISSUE THREAD

**Issue by ciscou** [romor/blind-control#2]
Hello!

First of all, thanks for sharing your project, and sorry to bother you with a n00b question. (disclaimer: I'm good at software, but very bad at electronics)

Thing is, I have this very basic setup, in which the RTS remote, with the battery removed, is powered up by the pi. Red cable is 3.3V, black is GND. I have removed the buttons.

![WhatsApp Image 2020-01-10 at 18 54 12](https://user-images.githubusercontent.com/433346/72175203-dc979f00-33db-11ea-8e2a-417a077bdfc5.jpeg)

Thing is, if I short-circuit two button pins with a cable, the blind will go up and down.

![WhatsApp Image 2020-01-10 at 18 54 31](https://user-images.githubusercontent.com/433346/72175285-19639600-33dc-11ea-8411-aba1c0c86042.jpeg)

But if I short circuit GND and one of the pins (I've tried them all), nothing happens. As far as I know, what the button does is exactly short-circuiting GND and the other pin, right?

![WhatsApp Image 2020-01-10 at 18 55 25](https://user-images.githubusercontent.com/433346/72175328-3b5d1880-33dc-11ea-9353-c0779f349083.jpeg)

Am I doing something stupid? I'd really like being able to control the blind with the pi but...

If I cannot do this this way, I'll try the opto capacitor way, but it looks unnecessarily complex as you say in the docs, also I'm not receiving my opto capacitors until the end of the month so I'll have to wait 😄 

Thanks in advance and sorry to bother!

**Comment by romor** [comment]
Difficult to judge remotely, but here some ideas:
- Do you have a multi-meter? I suggest to measure the voltages between the pins. Before the shortcut they should be around 3.3 V, afterwards zero. You can also measure against GND to compare.
- You unsoldered the push-buttons? I kept them inside. If I remember correctly, 2 pins each of them have a connection. Check it with the multi-meter. You may need to add the contact or use the other pin for activation.

Hope this helps.

**Comment by ciscou** [comment]
Well, I've received a brand new remote and a set of opto capacitors, and everything is working just fine. I bet it'd also work fine w/o the optos, probably the other remote was broken and most likely I broke it when I removed the buttons.

Thanks for your help, I'm closing the issue :)

**Comment by smarthead20** [comment]
Hi, 
     I think I've run into the same issue as you. If I use the raspi's 3.3 volt or one of the GPIO pins as output and set both to 0/1 and connect it to the pin on the button and then the ground on the remote or raspi nothing happens but if I use a wire and short circuit the 2 vertical pins or one of the pins and ground (see video) the blinds go up and down.  Is there a solution to this or will I have to use optocouplers/isolators like [this](https://www.amazon.com/Gikfun-OPTOCOUPLER-PC817C-Arduino-AE1143/dp/B01JG8EJVW/ref=sr_1_18?dchild=1&keywords=optocoupler&qid=1594135742&sr=8-18#customerReviews). Sorry if this is a noob question
[video](https://drive.google.com/file/d/1CYyXLN8S8b_U8lt1rxUwXjURMqM7kI7q/view?usp=sharing)
