### ISSUE TITLE
Same issue

### ISSUE THREAD

**Issue by JaiGupta13** [romor/blind-control#3]
If I use the raspi's 3.3 volt or one of the GPIO pins as output and set both to 0/1 and connect it to the pin on the button and then the ground on the remote or raspi nothing happens but if I use a wire and short circuit the 2 vertical pins or one of the pins and ground (see video) the blinds go up and down.  Is there a solution to this or will I have to use optocouplers/isolators like [this](https://www.amazon.com/Gikfun-OPTOCOUPLER-PC817C-Arduino-AE1143/dp/B01JG8EJVW/ref=sr_1_18?dchild=1&keywords=optocoupler&qid=1594135742&sr=8-18#customerReviews). 
[video](https://drive.google.com/file/d/1CYyXLN8S8b_U8lt1rxUwXjURMqM7kI7q/view?usp=sharing)

**Comment by romor** [comment]
Could you try the advice from the other thread?:

>  Measure the voltages between the pins. Before the shortcut they should be around 3.3 V, afterwards zero. You can also measure against GND to compare.
